/*
 * Copyright 2020-2021, 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_SIGNAL                              RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_SIGNAL                              TXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLpuartPins(void);              /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U368[F1]/U115[5]/J10[20]/J84[11A]/J84[11B] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_I2C5_SCL_PERIPHERAL                       LPI2C5   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_I2C5_SCL_SIGNAL                              SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U368[E2]/U115[4]/J10[18]/J84[12A]/J84[12B] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_I2C5_SDA_PERIPHERAL                       LPI2C5   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_I2C5_SDA_SIGNAL                              SDA   /*!< Signal name */

/* GPIO_AD_00 (coord N12), SIM1_TRXD/J44[C7]/J57[9]/CTP_INT/J48[29]/J25[15]/J9[14] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_PERIPHERAL                       GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_CHANNEL                            31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO                             GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO_PIN                           31U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO_PIN_MASK              (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_AD_01 (coord R14), SIM1_CLK/J44[C3]/J57[7]/CTP_RST_B/J48[28]/J10[4]/J25[13] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_CHANNEL                              0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO_PIN                             0U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO_PIN_MASK                (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_AD_02 (coord R13), SIM1_RST/J57[5]/J44[C2]/LCD_RST_B/J48[21]/J25[11]/J10[6] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_CHANNEL                              1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO_PIN                             1U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO_PIN_MASK                (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_AD_30 (coord K17), LPSPI1_SDO/U27[5]/J10[8]/Backlight_CTL/J48[34]/U46[4] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_CHANNEL                           29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO_PIN                          29U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO_PIN_MASK             (1U << 29U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

#define BOARD_INITSDCARD_IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK 0x8000U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_AD_32 (coord K16), ENET_MDC/SD1_CD_B/J15[9] */
/* Routed pin properties */
#define BOARD_INITSDCARD_ENET_MDC_PERIPHERAL                           CM7_GPIO3   /*!< Peripheral name */
#define BOARD_INITSDCARD_ENET_MDC_SIGNAL                         gpio_mux_io_cm7   /*!< Signal name */
#define BOARD_INITSDCARD_ENET_MDC_CHANNEL                                    31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSDCARD_ENET_MDC_GPIO                                 CM7_GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITSDCARD_ENET_MDC_GPIO_PIN                                   31U   /*!< GPIO pin number */
#define BOARD_INITSDCARD_ENET_MDC_GPIO_PIN_MASK                      (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_AD_34 (coord J16), 1588_EVENT0_IN/SD1_VSELECT */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_VSELECT_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_VSELECT_SIGNAL                        usdhc_vselect   /*!< Signal name */

/* GPIO_SD_B1_00 (coord B16), SD1_CMD/J15[3]/WIFI_SDIO_CMD/J54[11]/NVCC_SD */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_CMD_PERIPHERAL                               USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_CMD_SIGNAL                                usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B1_01 (coord D15), SD1_CLK/J15[5]/WIFI_SDIO_CLK/J54[9] */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_CLK_PERIPHERAL                               USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_CLK_SIGNAL                                usdhc_clk   /*!< Signal name */

/* GPIO_SD_B1_02 (coord C15), SD1_D0/J15[7]/WIFI_SDIO_D0/J54[13]/NVCC_SD */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_D0_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_D0_SIGNAL                                usdhc_data   /*!< Signal name */
#define BOARD_INITSDCARD_SD1_D0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_SD_B1_03 (coord B17), SD1_D1/J15[8]/WIFI_SDIO_D1/J54[15] */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_D1_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_D1_SIGNAL                                usdhc_data   /*!< Signal name */
#define BOARD_INITSDCARD_SD1_D1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_SD_B1_04 (coord B15), SD1_D2/J15[1]/WIFI_SDIO_D2/J54[17] */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_D2_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_D2_SIGNAL                                usdhc_data   /*!< Signal name */
#define BOARD_INITSDCARD_SD1_D2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_SD_B1_05 (coord A16), SD1_D3/J15[2]/WIFI_SDIO_D3/J54[19] */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD1_D3_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD1_D3_SIGNAL                                usdhc_data   /*!< Signal name */
#define BOARD_INITSDCARD_SD1_D3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_AD_35 (coord G17), 1588_EVENT0_OUT/SD_PWREN_B */
/* Routed pin properties */
#define BOARD_INITSDCARD_SD_PWREN_B_PERIPHERAL                            GPIO10   /*!< Peripheral name */
#define BOARD_INITSDCARD_SD_PWREN_B_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITSDCARD_SD_PWREN_B_CHANNEL                                   2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSDCARD_SD_PWREN_B_GPIO                                  GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITSDCARD_SD_PWREN_B_GPIO_PIN                                  2U   /*!< GPIO pin number */
#define BOARD_INITSDCARD_SD_PWREN_B_GPIO_PIN_MASK                     (1U << 2U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDCARD(void);                  /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
