################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_arc.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_img.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_label.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_layer.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_line.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_mask.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_rect.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_transform.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_triangle.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_buf.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_cache.c \
C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_decoder.c 

C_DEPS += \
./lvgl/lvgl/src/draw/lv_draw.d \
./lvgl/lvgl/src/draw/lv_draw_arc.d \
./lvgl/lvgl/src/draw/lv_draw_img.d \
./lvgl/lvgl/src/draw/lv_draw_label.d \
./lvgl/lvgl/src/draw/lv_draw_layer.d \
./lvgl/lvgl/src/draw/lv_draw_line.d \
./lvgl/lvgl/src/draw/lv_draw_mask.d \
./lvgl/lvgl/src/draw/lv_draw_rect.d \
./lvgl/lvgl/src/draw/lv_draw_transform.d \
./lvgl/lvgl/src/draw/lv_draw_triangle.d \
./lvgl/lvgl/src/draw/lv_img_buf.d \
./lvgl/lvgl/src/draw/lv_img_cache.d \
./lvgl/lvgl/src/draw/lv_img_decoder.d 

OBJS += \
./lvgl/lvgl/src/draw/lv_draw.o \
./lvgl/lvgl/src/draw/lv_draw_arc.o \
./lvgl/lvgl/src/draw/lv_draw_img.o \
./lvgl/lvgl/src/draw/lv_draw_label.o \
./lvgl/lvgl/src/draw/lv_draw_layer.o \
./lvgl/lvgl/src/draw/lv_draw_line.o \
./lvgl/lvgl/src/draw/lv_draw_mask.o \
./lvgl/lvgl/src/draw/lv_draw_rect.o \
./lvgl/lvgl/src/draw/lv_draw_transform.o \
./lvgl/lvgl/src/draw/lv_draw_triangle.o \
./lvgl/lvgl/src/draw/lv_img_buf.o \
./lvgl/lvgl/src/draw/lv_img_cache.o \
./lvgl/lvgl/src/draw/lv_img_decoder.o 


# Each subdirectory must supply rules for building sources it contributes
lvgl/lvgl/src/draw/lv_draw.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_arc.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_arc.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_img.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_img.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_label.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_label.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_layer.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_layer.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_line.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_line.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_mask.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_mask.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_rect.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_rect.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_transform.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_transform.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_draw_triangle.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_draw_triangle.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_img_buf.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_buf.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_img_cache.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_cache.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lvgl/lvgl/src/draw/lv_img_decoder.o: C:/Guna/AUG4/sdk/Core/lvgl/lvgl/src/draw/lv_img_decoder.c lvgl/lvgl/src/draw/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__NEWLIB__ -DCPU_MIMXRT1176DVMAA -DCPU_MIMXRT1176DVMAA_cm7 -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DUSE_SDRAM -DDATA_SECTION_IS_CACHEABLE=1 -DSDK_DEBUGCONSOLE=1 -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 -DLV_CONF_INCLUDE_SIMPLE=1 -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 -DTRIOX_BOARD_CONFIG=1 -DMCUXPRESSO_SDK -DSD_ENABLED -DSDK_I2C_BASED_COMPONENT_USED=1 -DVG_COMMAND_CALL=1 -DVG_TARGET_FAST_CLEAR=0 -DSERIAL_PORT_TYPE_UART=1 -DSDK_OS_FREE_RTOS -D__NXP_MSDK__ -DCR_INTEGER_PRINTF -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\Guna\AUG4\sdk\Core\source" -I"C:\Guna\AUG4\sdk\Core\video" -I"C:\Guna\AUG4\sdk\Core\drivers" -I"C:\Guna\AUG4\sdk\Core\touchpanel" -I"C:\Guna\AUG4\sdk\Core\sdmmc\host" -I"C:\Guna\AUG4\sdk\Core\sdmmc\inc" -I"C:\Guna\AUG4\sdk\Core\component\gpio" -I"C:\Guna\AUG4\sdk\Core\fatfs\source\fsl_sd_disk" -I"C:\Guna\AUG4\sdk\Core\fatfs\source" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\core\inc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\decoder\plus\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\inc" -I"C:\Guna\AUG4\sdk\Core\vglite\font" -I"C:\Guna\AUG4\sdk\Core\vglite\font\mcufont\decoder" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLite\rtos" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel" -I"C:\Guna\AUG4\sdk\Core\vglite\VGLiteKernel\rtos" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src" -I"C:\Guna\AUG4\sdk\Core\lvgl\lvgl\src\font" -I"C:\Guna\AUG4\sdk\Core\lvgl" -I"C:\Guna\AUG4\sdk\Core\device" -I"C:\Guna\AUG4\sdk\Core\utilities" -I"C:\Guna\AUG4\sdk\Core\component\uart" -I"C:\Guna\AUG4\sdk\Core\component\serial_manager" -I"C:\Guna\AUG4\sdk\Core\component\lists" -I"C:\Guna\AUG4\sdk\mcuxpresso\startup" -I"C:\Guna\AUG4\sdk\Core\xip" -I"C:\Guna\AUG4\sdk\Core\sdmmc\osa" -I"C:\Guna\AUG4\sdk\Core\component\osa" -I"C:\Guna\AUG4\sdk\Core\board" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\include" -I"C:\Guna\AUG4\sdk\Core\freertos\freertos-kernel\portable\GCC\ARM_CM4F" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\api\svc" -I"C:\Guna\AUG4\sdk\Core\openh264\codec\common\inc" -I"C:\Guna\AUG4\sdk\Core\CMSIS" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\abstractions\posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\freertos_plus\standard\freertos_plus_posix\include" -I"C:\Guna\AUG4\sdk\Core\source\freertos_libraries\c_sdk\standard\common\include\private" -I"C:\Guna\AUG4\generated" -I"C:\Guna\AUG4\custom" -I"C:\Guna\AUG4\generated\guider_customer_fonts" -I"C:\Guna\AUG4\generated\guider_fonts" -I"C:\Guna\AUG4\sdk\Core\rlottie" -O0 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -fno-builtin -Wno-format -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-lvgl-2f-lvgl-2f-src-2f-draw

clean-lvgl-2f-lvgl-2f-src-2f-draw:
	-$(RM) ./lvgl/lvgl/src/draw/lv_draw.d ./lvgl/lvgl/src/draw/lv_draw.o ./lvgl/lvgl/src/draw/lv_draw_arc.d ./lvgl/lvgl/src/draw/lv_draw_arc.o ./lvgl/lvgl/src/draw/lv_draw_img.d ./lvgl/lvgl/src/draw/lv_draw_img.o ./lvgl/lvgl/src/draw/lv_draw_label.d ./lvgl/lvgl/src/draw/lv_draw_label.o ./lvgl/lvgl/src/draw/lv_draw_layer.d ./lvgl/lvgl/src/draw/lv_draw_layer.o ./lvgl/lvgl/src/draw/lv_draw_line.d ./lvgl/lvgl/src/draw/lv_draw_line.o ./lvgl/lvgl/src/draw/lv_draw_mask.d ./lvgl/lvgl/src/draw/lv_draw_mask.o ./lvgl/lvgl/src/draw/lv_draw_rect.d ./lvgl/lvgl/src/draw/lv_draw_rect.o ./lvgl/lvgl/src/draw/lv_draw_transform.d ./lvgl/lvgl/src/draw/lv_draw_transform.o ./lvgl/lvgl/src/draw/lv_draw_triangle.d ./lvgl/lvgl/src/draw/lv_draw_triangle.o ./lvgl/lvgl/src/draw/lv_img_buf.d ./lvgl/lvgl/src/draw/lv_img_buf.o ./lvgl/lvgl/src/draw/lv_img_cache.d ./lvgl/lvgl/src/draw/lv_img_cache.o ./lvgl/lvgl/src/draw/lv_img_decoder.d ./lvgl/lvgl/src/draw/lv_img_decoder.o

.PHONY: clean-lvgl-2f-lvgl-2f-src-2f-draw

