/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_SNVS_00 (coord R10), J42[3] */
/* Routed pin properties */
#define BOARD_INITPINS_BUTTON_RIGHT_PERIPHERAL                            GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_BUTTON_RIGHT_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BUTTON_RIGHT_CHANNEL                                   3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BUTTON_RIGHT_GPIO                                  GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BUTTON_RIGHT_GPIO_PIN                                  3U   /*!< GPIO pin number */
#define BOARD_INITPINS_BUTTON_RIGHT_GPIO_PIN_MASK                     (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_SNVS_01 (coord P10), J42[4] */
/* Routed pin properties */
#define BOARD_INITPINS_BUTTON_LEFT_PERIPHERAL                             GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_BUTTON_LEFT_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BUTTON_LEFT_CHANNEL                                    4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BUTTON_LEFT_GPIO                                   GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BUTTON_LEFT_GPIO_PIN                                   4U   /*!< GPIO pin number */
#define BOARD_INITPINS_BUTTON_LEFT_GPIO_PIN_MASK                      (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_SNVS_02 (coord L9), J42[5] */
/* Routed pin properties */
#define BOARD_INITPINS_BUTTON_DOWN_PERIPHERAL                             GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_BUTTON_DOWN_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BUTTON_DOWN_CHANNEL                                    5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BUTTON_DOWN_GPIO                                   GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BUTTON_DOWN_GPIO_PIN                                   5U   /*!< GPIO pin number */
#define BOARD_INITPINS_BUTTON_DOWN_GPIO_PIN_MASK                      (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_SNVS_03 (coord M10), J42[6] */
/* Routed pin properties */
#define BOARD_INITPINS_BUTTON_UP_PERIPHERAL                               GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_BUTTON_UP_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BUTTON_UP_CHANNEL                                      6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BUTTON_UP_GPIO                                     GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BUTTON_UP_GPIO_PIN                                     6U   /*!< GPIO pin number */
#define BOARD_INITPINS_BUTTON_UP_GPIO_PIN_MASK                        (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_AD_06 (coord N13), USB_OTG2_OC/U18[A2]/J9[10]/AUD_INT */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_TX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_AD_07 (coord T17), USB_OTG2_PWR/WL_DEV_WAKE/U354[10]/J10[2] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_RX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_RX_SIGNAL                                         RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U368[F1]/U115[5]/J10[20]/J84[11A]/J84[11B] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_I2C5_SCL_PERIPHERAL                       LPI2C5   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_I2C5_SCL_SIGNAL                              SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U368[E2]/U115[4]/J10[18]/J84[12A]/J84[12B] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_I2C5_SDA_PERIPHERAL                       LPI2C5   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_I2C5_SDA_SIGNAL                              SDA   /*!< Signal name */

/* GPIO_AD_00 (coord N12), SIM1_TRXD/J44[C7]/J57[9]/CTP_INT/J48[29]/J25[15]/J9[14] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_PERIPHERAL                       GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_CHANNEL                            31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO                             GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO_PIN                           31U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_TRXD_GPIO_PIN_MASK              (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_AD_01 (coord R14), SIM1_CLK/J44[C3]/J57[7]/CTP_RST_B/J48[28]/J10[4]/J25[13] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_CHANNEL                              0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO_PIN                             0U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_CLK_GPIO_PIN_MASK                (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_AD_02 (coord R13), SIM1_RST/J57[5]/J44[C2]/LCD_RST_B/J48[21]/J25[11]/J10[6] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_CHANNEL                              1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO_PIN                             1U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_SIM1_RST_GPIO_PIN_MASK                (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_AD_30 (coord K17), LPSPI1_SDO/U27[5]/J10[8]/Backlight_CTL/J48[34]/U46[4] */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_CHANNEL                           29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO_PIN                          29U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_LPSPI1_SDO_GPIO_PIN_MASK             (1U << 29U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
